### ISSUE TITLE
PostgresDbClient returns invalid results in method GetSimilarAsync

### ISSUE THREAD

**Issue by esbencarlsen** [microsoft/kernel-memory-extension-example#12]
PostgresDbClient can return invalid result in method GetSimilarAsync when there are multiple results in the result set because similarity is not returned ordered from postgres.

In class PostgresDbClient line 423 the following check - potentially - breaks the reading while loop when similarity is returned unordered, so not all results are returned.

```
if (similarity < minSimilarity)
{
    run = false;
    continue;
}
```

Potential fix:
Change existing query from
```
cmd.CommandText = @$"
    SELECT {columns}, 1 - ({this._colEmbedding} <=> @embedding) AS {similarityActualValue}
    FROM {tableName}
    WHERE {filterSql}
    LIMIT @limit
    OFFSET @offset
";
```
to return ordered by similarity desc
```
cmd.CommandText = @$"
    SELECT {columns}, 1 - ({this._colEmbedding} <=> @embedding) AS {similarityActualValue}
    FROM {tableName}
    WHERE {filterSql}
    ORDER BY {similarityActualValue} DESC
    LIMIT @limit
    OFFSET @offset
";
```

**Comment by dluc** [comment]
thank you @esbencarlsen. FYI, we've moved the code to https://github.com/microsoft/kernel-memory/tree/main/extensions/Postgres - where we will also fix the bug. The package name has also changed to [Microsoft.KernelMemory.MemoryDb.Postgres](https://www.nuget.org/packages/Microsoft.KernelMemory.MemoryDb.Postgres)
